<?php
/**
 * Template Name: 報酬表
**/

get_header(); ?>
<main id="main">
    <section class="price-bg main-bg" data-aos="fade-up">
    </section>

    <section data-aos="fade-up">
	<div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h1 class="mb-5 h1 text-center">報酬のご案内</h1>
                <p>相談料等は正式にご依頼頂いてから発生しますので、安心してご相談下さい。<br>下記報酬表はあくまで目安となります。<br>ご依頼時に正式な見積もりをご請求させていただきます。</p>
            </div>
        </div>
    </div>
    </section>
    
    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-10 mx-auto">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td rowspan="18">会社設立・事業サポート</td>
                                <td>契約書新規作成</td>
                                <td>基本作成費用50,000〜<br>
                                5,000/枚</td>
                            </tr>
                            <tr>
                                <td>契約書修正・チェック</td>
                                <td>基本費用20,000〜<br>
                                1,000/枚</td>
                            </tr>
                            <tr>
                                <td>英文契約書加算</td>
                                <td>基本費用＋20,000〜<br>
                                ＋2,000/枚</td>
                            </tr>
                            <tr>
                                <td>就業規則作成（従業員10人未満）</td>
                                <td>基本作成費用80,000〜<br>
                                5,000/枚</td>
                            </tr>
                            <tr>
                                <td>賃金規程・賞与規定等作成</td>
                                <td>基本作成費用60,000〜<br>
                                5,000/枚</td>
                            </tr>
                            <tr>
                                <td>議事録・プライバシーポリシー作成</td>
                                <td>基本作成費用30,000〜<br>
                                5,000/枚</td>
                            </tr>
                            <tr>
                                <td>定款作成</td>
                                <td>基本作成費用30,000〜<br>
                                5,000/枚</td>
                            </tr>
                            <tr>
                                <td>定款変更</td>
                                <td>10,000〜</td>
                            </tr>
                            <tr>
                                <td>株主名簿作成</td>
                                <td>10,000</td>
                            </tr>
                            <tr>
                                <td>株式会社設立</td>
                                <td>100,000</td>
                            </tr>
                            <tr>
                                <td>合同会社設立</td>
                                <td>70,000</td>
                            </tr>
                            <tr>
                                <td>一般社団法人設立</td>
                                <td>100,000</td>
                            </tr>
                            <tr>
                                <td>NPO法人設立</td>
                                <td>200,000</td>
                            </tr>
                            <tr>
                                <td>助成金申請関連書類作成</td>
                                <td>30,000〜</td>
                            </tr>
                            <tr>
                                <td>帳簿記入・管理</td>
                                <td>100/仕訳</td>
                            </tr>
                            <tr>
                                <td>ホームページ制作（新規）</td>
                                <td>基本費用80,000〜<br>
                                ページ追加20,000/枚</td>
                            </tr>
                            <tr>
                                <td>ホームページ管理</td>
                                <td>5,000〜/月</td>
                            </tr>
                            <tr>
                                <td>行政書士顧問</td>
                                <td>20,000〜/月</td>
                            </tr>
                            <tr>
                                <td rowspan="9">遺言・相続手続き</td>
                                <td>遺言原案作成</td>
                                <td>50,000</td>
                            </tr>
                            <tr>
                                <td>遺言公正証書証人</td>
                                <td>30,000/人</td>
                            </tr>
                            <tr>
                                <td>公正証書遺言作成フルサポート</td>
                                <td>150,000</td>
                            </tr>
                            <tr>
                                <td>遺言執行者就任</td>
                                <td>30,000<br>
                                執行時遺産総額の1%〜3%</td>
                            </tr>
                            <tr>
                                <td>遺産分割協議書作成のための戸籍収集</td>
                                <td>30,000/直系</td>
                            </tr>
                            <tr>
                                <td>遺産分割協議書作成</td>
                                <td>70,000</td>
                            </tr>
                            <tr>
                                <td>相続手続きフルサポート</td>
                                <td>300,000</td>
                            </tr>
                            <tr>
                                <td>死後事務委任契約公正証書原案作成</td>
                                <td>50,000</td>
                            </tr>
                            <tr>
                                <td>死後事務の受任</td>
                                <td>50,000〜</td>
                            </tr>
                            <tr>
                                <td rowspan="19">許認可等手続き</td>
                                <td>建設業許可申請（新規・知事許可）</td>
                                <td>150,000</td>
                            </tr>
                            <tr>
                                <td>建設業許可申請（更新）</td>
                                <td>70,000</td>
                            </tr>
                            <tr>
                                <td>建設業許可変更届（経管・専技・決算等）</td>
                                <td>50,000/項目</td>
                            </tr>
                            <tr>
                                <td>建設業経営状況分析</td>
                                <td>40,000</td>
                            </tr>
                            <tr>
                                <td>建設業経営事項審査</td>
                                <td>80,000</td>
                            </tr>
                            <tr>
                                <td>産業廃棄物収集運搬（積替え保管を含まない）<br>
                                許可申請（新規）</td>
                                <td>120,000</td>
                            </tr>
                            <tr>
                                <td>産業廃棄物収集運搬（積替え保管を含まない）<br>
                                許可申請（更新）</td>
                                <td>70,000</td>
                            </tr>
                            <tr>
                                <td>宅建業免許申請（新規・知事）</td>
                                <td>80,000</td>
                            </tr>
                            <tr>
                                <td>宅建業免許申請（更新・知事）</td>
                                <td>70,000</td>
                            </tr>
                            <tr>
                                <td>旅行業登録申請（2種・3種）</td>
                                <td>160,000</td>
                            </tr>
                            <tr>
                                <td>旅行業登録申請（1種）</td>
                                <td>200,000</td>
                            </tr>
                            <tr>
                                <td>電気通信事業届出</td>
                                <td>60,000</td>
                            </tr>
                            <tr>
                                <td>飲食業許可申請</td>
                                <td>40,000</td>
                            </tr>
                            <tr>
                                <td>深夜酒類提供飲食店営業届出</td>
                                <td>100,000</td>
                            </tr>
                            <tr>
                                <td>風俗営業許可（2号許可）申請</td>
                                <td>140,000</td>
                            </tr>
                            <tr>
                                <td>古物商許可申請</td>
                                <td>45,000</td>
                            </tr>
                            <tr>
                                <td>インターネット異性紹介事業届出</td>
                                <td>45,000</td>
                            </tr>
                            <tr>
                                <td>住宅宿泊事業届出</td>
                                <td>100,000</td>
                            </tr>
                            <tr>
                                <td>道路使用許可申請</td>
                                <td>42,000</td>
                            </tr>
                            <tr>
                                <td rowspan="4">国外関係</td>
                                <td>在留資格認定証明書交付申請</td>
                                <td>120,000</td>
                            </tr>
                            <tr>
                                <td>在留資格認定証明書交付申請（書類のみ）</td>
                                <td>100,000</td>
                            </tr>
                            <tr>
                                <td>住民票・戸籍の英訳（翻訳）<br>
                                翻訳証明書</td>
                                <td>10,000/枚<br>
                                10,000</td>
                            </tr>
                            <tr>
                                <td>パスポート申請</td>
                                <td>20,000</td>
                            </tr>
                            <tr>
                                <td rowspan="5">自動車関係</td>
                                <td>車庫証明</td>
                                <td>10,000</td>
                            </tr>
                            <tr>
                                <td>図面作成（簡易測量込み）</td>
                                <td>4,000</td>
                            </tr>
                            <tr>
                                <td>軽自動車登録申請（軽自動車の名義変更・住所変更等）</td>
                                <td>20,000〜</td>
                            </tr>
                            <tr>
                                <td>軽貨物運送事業届出（黒ナンバー）</td>
                                <td>30,000</td>
                            </tr>
                            <tr>
                                <td>交通事故 示談契約書作成</td>
                                <td>32,000</td>
                            </tr>
                            <tr>
                                <td rowspan="4">その他市民法務</td>
                                <td>離婚協議書作成</td>
                                <td>60,000</td>
                            </tr>
                            <tr>
                                <td>和解契約書作成</td>
                                <td>45,000</td>
                            </tr>
                            <tr>
                                <td>覚書等作成</td>
                                <td>4,200/枚</td>
                            </tr>
                            <tr>
                                <td>内容証明郵便作成（クーリング・オフ等）</td>
                                <td>20,000〜</td>
                            </tr>
                            <tr>
                                <td rowspan="5">その他の書面・日当</td>
                                <td>その他考案を要する書面</td>
                                <td>8,000/枚</td>
                            </tr>
                            <tr>
                                <td>その他考案を要しない書面</td>
                                <td>4,000/枚</td>
                            </tr>
                            <tr>
                                <td>各副本</td>
                                <td>500/枚</td>
                            </tr>
                            <tr>
                                <td>日当・調査費用（資格者・半日）</td>
                                <td>30,000</td>
                            </tr>
                            <tr>
                                <td>日当・調査費用（資格者・一日）</td>
                                <td>50,000</td>
                            </tr>
                            <tr>
                                <td colspan="2">郵送費・交通費・書類取得費用・申請費用・官公署費用等</td>
                                <td>実際にかかった費用</td>
                            </tr>
                            <tr>
                                <td colspan="3">
                                    <div align="right">
                                        [※1] 単位：円　/　[※2] 消費税10%を加算します。<br>
                                        [※3] 同時に複数のご依頼を頂く場合，割引を行うことがあります。
                                        <p>&nbsp;</p>
                                        <div>
                                            &nbsp;
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="3">
                                    <div align="right">
                                        2023年6月〜
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</main>
<?php get_footer(); ?>